name: Push Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Use a Node.js version compatible with clasp

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Authenticate clasp
      - uses: daikikatsuragawa/clasp-action@v1.1.0
        with:
          # accessToken: ${{ secrets.ACCESS_TOKEN }}
          # idToken: ${{ secrets.ID_TOKEN }}
          # refreshToken: ${{ secrets.REFRESH_TOKEN }}
          clientId: ${{ secrets.CLIENT_ID }}
          clientSecret: ${{ secrets.CLIENT_SECRET }}
          scriptId: ${{ secrets.SCRIPT_ID }}
          command: 'push'
        # run: |
        #   echo  ${{ secrets.CLASP_PASSWORD }} | clasp login --no-localhost
        #   clasp setting scriptId ${{ secrets.SCRIPT_ID }}

      - name: Push to Google Apps Script
        run: clasp push
