name: Push Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Use a Node.js version compatible with clasp

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Authenticate clasp
        run: |
          echo  ${{ secrets.CLASP_PASSWORD }} | clasp login --no-localhost
          clasp setting scriptId ${{ secrets.SCRIPT_ID }}
          
      - name: Push to Google Apps Script
        run: clasp push
