# Push to Google App Script
name: Push Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17'  # Use a Node.js version compatible with clasp

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Authenticate clasp
        run: |
          echo ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }} > service-account-key.json
          clasp login --creds service-account-key.json
          
      - name: Push to Google Apps Script
        run: clasp push
